name: Build And Pushlish

on: 
  push:
    branches: [ main ]

jobs:

  build-with-maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 100

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ToolSetEncodeTransformer_Jar
        path: target/ToolSetEncodeTransformer.jar

    - name: Generate Javadoc
      run: mvn --batch-mode javadoc:javadoc && cp -r ./target/site/apidocs ./javadoc 

    - name: Packup ApiDoc
      uses: actions/upload-artifact@v2
      with:
        name: ToolSetEncodeTransformer_ApiDoc
        path: javadoc

  pull-to-docker-hub:

    runs-on: ubuntu-latest
    needs: build-with-maven

    steps:
    - uses: actions/checkout@v2
    
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ToolSetEncodeTransformer_Jar
        path: target

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/toolset_encodetransformer:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}